In [1]:
import os
import sys
project_root_path, _ =  os.path.split(os.path.abspath("."))
sys.path.append(project_root_path)

In [2]:
from torchvision.datasets import MNIST

In [3]:
raw_data_local_dir = os.path.join(project_root_path, 'data', 'raw_data', 'local')


In [4]:
mnist_dir = os.path.join(raw_data_local_dir, 'mnist')
mnist_train = MNIST(root=mnist_dir, train=True, download=True)
mnist_test = MNIST(root=mnist_dir, train=False, download=True)

Extracting /opt/ml/ml-template/data/raw_data/local/mnist/MNIST/raw/train-images-idx3-ubyte.gz to /opt/ml/ml-template/data/raw_data/local/mnist/MNIST/raw


Extracting /opt/ml/ml-template/data/raw_data/local/mnist/MNIST/raw/train-labels-idx1-ubyte.gz to /opt/ml/ml-template/data/raw_data/local/mnist/MNIST/raw



Extracting /opt/ml/ml-template/data/raw_data/local/mnist/MNIST/raw/t10k-images-idx3-ubyte.gz to /opt/ml/ml-template/data/raw_data/local/mnist/MNIST/raw


Extracting /opt/ml/ml-template/data/raw_data/local/mnist/MNIST/raw/t10k-labels-idx1-ubyte.gz to /opt/ml/ml-template/data/raw_data/local/mnist/MNIST/raw
Processing...
Done!


/opt/conda/lib/python3.8/site-packages/torchvision/datasets/mnist.py:469: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:141.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)


In [5]:
next(iter(mnist_train))

(<PIL.Image.Image image mode=L size=28x28 at 0x7F8289C821F0>, 5)

In [6]:
len(mnist_train)

60000

In [12]:
print(len(mnist_train.data))
print(type(mnist_train.data))
print(mnist_train.data.shape)
print(len(mnist_train.train_labels))

60000
<class 'torch.Tensor'>
torch.Size([60000, 28, 28])
60000


In [13]:
mnist_train[0]

(<PIL.Image.Image image mode=L size=28x28 at 0x7F828834E5E0>, 5)

In [16]:
import torch.nn as nn
from importlib import import_module

In [24]:
def test(**kargs):
    if kargs.keys().__contains__('a'):
        print('hhh')

In [27]:
test(a='a')

hhh


In [19]:
print(type(l1) == type(l2))

True


In [1]:
import numpy as np

l = np.array([1,2,3,4,5,6])
l

array([1, 2, 3, 4, 5, 6])

In [9]:
from sklearn.model_selection import StratifiedKFold
X = np.zeros((10, 2))
y = np.random.randint(0, 10, (10, 1))
print(X, y)

skf = StratifiedKFold(n_splits=3)
folds = []
for train_idx, valid_idx in skf.split(X, y):
    print('-'*10)
    print(train_idx, valid_idx)
    folds.append((train_idx, valid_idx))

print(folds)



[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] [[6]
 [4]
 [3]
 [5]
 [4]
 [0]
 [9]
 [9]
 [0]
 [4]]
----------
[2 3 4 7 8 9] [0 1 5 6]
----------
[0 1 3 5 6 7 9] [2 4 8]
----------
[0 1 2 4 5 6 8] [3 7 9]
[(array([2, 3, 4, 7, 8, 9]), array([0, 1, 5, 6])), (array([0, 1, 3, 5, 6, 7, 9]), array([2, 4, 8])), (array([0, 1, 2, 4, 5, 6, 8]), array([3, 7, 9]))]


/opt/conda/lib/python3.8/site-packages/sklearn/model_selection/_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(("The least populated class in y has only %d"


In [10]:
import os
import sys
project_root_path, _ =  os.path.split(os.path.abspath("."))
sys.path.append(project_root_path)



In [11]:
from data.proxy import MNISTTrainDataset

dataset = MNISTTrainDataset()

Extracting ../raw_data/local/mnist/MNIST/raw/train-images-idx3-ubyte.gz to ../raw_data/local/mnist/MNIST/raw



Extracting ../raw_data/local/mnist/MNIST/raw/train-labels-idx1-ubyte.gz to ../raw_data/local/mnist/MNIST/raw


Extracting ../raw_data/local/mnist/MNIST/raw/t10k-images-idx3-ubyte.gz to ../raw_data/local/mnist/MNIST/raw


Extracting ../raw_data/local/mnist/MNIST/raw/t10k-labels-idx1-ubyte.gz to ../raw_data/local/mnist/MNIST/raw
Processing...
Done!


/opt/conda/lib/python3.8/site-packages/torchvision/datasets/mnist.py:469: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:141.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)


In [ ]:
get_k_fold_loaders()